FROM node:latest

# Install Node.js and other dependencies
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Create upload directories
RUN mkdir -p public/uploads/items public/uploads/profiles

# Expose ports
EXPOSE 3000

# Start Node.js app
CMD ["npm", "start"] 
